name: developer
parent: default

matches:
  - trigger: ":gitcrypt"
    replace: " filter=git-crypt diff=git-crypt"
  - trigger: ":details"
    replace: "<details><summary>View</summary><p>\n\n</p></details>"
  - trigger: ":titleimage"
    replace: '<h1>TITLE</h1><p><img align="right" style="float" height="45px" href="#" src="#"></p>'